/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrlCheckerRouteImport } from './routes/url-checker'
import { Route as TextScannerRouteImport } from './routes/text-scanner'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const UrlCheckerRoute = UrlCheckerRouteImport.update({
  id: '/url-checker',
  path: '/url-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const TextScannerRoute = TextScannerRouteImport.update({
  id: '/text-scanner',
  path: '/text-scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/text-scanner': typeof TextScannerRoute
  '/url-checker': typeof UrlCheckerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/text-scanner': typeof TextScannerRoute
  '/url-checker': typeof UrlCheckerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reports': typeof ReportsRoute
  '/text-scanner': typeof TextScannerRoute
  '/url-checker': typeof UrlCheckerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/reports' | '/text-scanner' | '/url-checker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/reports' | '/text-scanner' | '/url-checker'
  id: '__root__' | '/' | '/auth' | '/reports' | '/text-scanner' | '/url-checker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ReportsRoute: typeof ReportsRoute
  TextScannerRoute: typeof TextScannerRoute
  UrlCheckerRoute: typeof UrlCheckerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/url-checker': {
      id: '/url-checker'
      path: '/url-checker'
      fullPath: '/url-checker'
      preLoaderRoute: typeof UrlCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-scanner': {
      id: '/text-scanner'
      path: '/text-scanner'
      fullPath: '/text-scanner'
      preLoaderRoute: typeof TextScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ReportsRoute: ReportsRoute,
  TextScannerRoute: TextScannerRoute,
  UrlCheckerRoute: UrlCheckerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
